### PR TITLE
Adds drag and drop of social

### PR DESCRIPTION
**Pull request by tylerturdenpants**
will remove from readme once tested.

### CODE REVIEW

**Comment by amyrlam** [comment]
💯

**Review by jayjayjpg — APPROVED** [review]
draganddrop

Just tested the update locally in browser mode and this works :sparkles: Thank you for another great upgrade this week @tylerturdenpants!

**Comment by amyrlam** [comment]
just saw it in action, nice work!

**Comment by amyrlam** [comment]
What's confusing is this seemed to work for https://blog.emberjs.com/2019/02/22/the-ember-times-issue-86.html before re: my above comment on Feb 24, but it no longer works for the same URL. So going to propose a revert

**Pull request merged**
