### PR TITLE
Rollback: remove buggy features

### PR DESCRIPTION
**Pull request by amyrlam**
Not sure if the interactive rebase worked, testing

### CODE REVIEW

**Comment by tylerturdenpants** [comment]
LGTM

**Comment by amyrlam** [comment]
I did an interactive rebase to 9a07176, but keep the `signInPage` URL change. 

I'm surprised that the dropped commits don't show up(?) in the PR, following https://github.blog/2015-06-08-how-to-undo-almost-anything-with-git/#mass-undo-redo, but this is working for issues # 86 and 90 so let's move forward with it to have a clean master.

**Comment by amyrlam** [comment]
I mucked something in this "fix". Filed an issue, will investigate https://github.com/ember-learn/ember-times-tools/issues/23, let me know if have any ideas.

(Other existing issues are lower priority)

**Comment by tylerturdenpants** [comment]
what are you doing to me?

**Comment by amyrlam** [comment]
? not sure what you mean

I've created an Ember Times project, we are project managing now! https://github.com/orgs/ember-learn/projects/18?add_cards_query=is%3Aopen

**Pull request merged**
