### PR TITLE
Puppeteer - remove extra spaces

### PR DESCRIPTION
**Pull request by tylerturdenpants**
Removes extra spaces.  Solves #3

### CODE REVIEW

**Review by amyrlam — APPROVED** [review]
👍 lgtm, let's merge and give it a try tmrw?

**Comment by jayjayjpg** [comment]
Agree, thank you for the awesome update @tylerturdenpants! ✨

**Comment by amyrlam** [comment]
```amyrlam@youthphase emberjs-times-tools (master)  $ node create-goodbits-template.js --botemail="$GOODBITS_USER_EMAIL" --botpassword="$GOODBITS_USER_PASSWORD" --engine="slimerjs" --botblogurl="https://emberjs.com/blog/2018/12/21/the-ember-times-issue-78.html"
Visiting https://emberjs.com/blog/2018/12/21/the-ember-times-issue-78.html ...
Collected text content from 9 sections to copy.
Visiting https://goodbits.io/users/sign_in ...
Logged in successfully ✨
Adding intro....
Added intro. ✨
Editing content (1/8)
Finished editing content (1/8)
Editing content (2/8)
Finished editing content (2/8)
Editing content (3/8)
(node:6291) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __puppeteer_evaluation_script__:7:31
    at ExecutionContext.evaluateHandle (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:124:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:144:27)
    at ExecutionContext.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:145:23)
    at Frame.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/FrameManager.js:447:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.evaluate (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/Page.js:777:43)
    at Page.<anonymous> (/Users/amyrlam/src/ember/emberjs-times-tools/node_modules/puppeteer/lib/helper.js:145:23)
    at addContentBlockRoutine (/Users/amyrlam/src/ember/emberjs-times-tools/create-goodbits-template.js:263:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

then it just hangs...

I rolled back to a prior commit to get to finish.

I will try to take a further look 🔜

**Comment by tylerturdenpants** [comment]
I’ll debug. I suspect a null value is coming. I will guard.

**Pull request merged**
